### ISSUE TITLE
좌석 정보 버그

### ISSUE THREAD

**Issue by seungyoonHan** [yimjisu/GLACE_Team3#44]
시간 및 좌석에 아무 것도 보이지 않는 버그가 있습니다. mac 사용중인데, 그 때문인지 아닌지는 모르겠습니다
<img width="1552" alt="스크린샷 2021-12-05 오후 4 11 08" src="https://user-images.githubusercontent.com/70496968/144737321-21f6a67f-b42e-494e-97c8-f75b13513fb8.png">
.

**Comment by yimjisu** [comment]
11월 24일 / 26일만 지금 좌석 정보가 있는 상태여서 더 추가하면 될 것 같아요!
